name: Build and Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'oracle'
          java-version: '17'

      # Step 3: Build the Spring Boot application
      - name: Build with Maven
        run:  mvn clean package

      # Step 4: Upload JAR file to Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ecommerce-aws-assinment-env
          environment_name: ecommerce-aws-assinment-env-env
          version_label: ${{ github.run_number }}
          region: ap-south-1
          deployment_package: target/ecommerce-0.0.1-SNAPSHOT.jar 
